[package]
name = "jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = { version = "10", default-features = false, features = ["aws_lc_rs"] }
serde = {version = "1.0", features = ["derive"] }