[package]
name = "sqlite_todo"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.35.0", features = ["bundled"] }
dirs = "5.0"

[profile.release]
lto = "thin"
codegen-units = 16
strip = true
opt-level = "z"
