[package]
name = "sqlite_quries"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
rusqlite = { version = "0.38", features = ["bundled"]}